stages:
  - build
  - deploy

# Etapa 1: Construcción de imagen Docker
build_image:
  stage: build
  tags:
    - test
  script:
    - echo "Construyendo imagen Docker con Java..."
    - docker build -t mi-app-java:latest .

# Etapa 2: Despliegue (levantar contenedor)
deploy_container:
  stage: deploy
  script:
    - echo "Deteniendo y eliminando contenedor existente si existe..."
    - docker stop mi-app || true
    - docker rm mi-app || true
    - echo "Levantando contenedor..."
    - docker run -d --name mi-app -p 8081:8080 mi-app-java:latest
  tags:
    - test
